Merged Mining Capabilities Extension
rsksmart/RSKIPs pull request #177
Opened 2020-09-30 21:58 UTC by M-Picco

2020-10-01 00:50 UTC, martinmedina approved these changes
LGTM!

2020-10-08 19:36 UTC, SergioDemianLerner requested changes

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +
"summarized data" is not clear. I suggest  "a short array of data" or "an additional hash digest" or something like that.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +The ability to extend the merged mining process to include information other than the block’s hash in the merged mining hash offers a myriad of new applications to the miner’s hashing power without a
"in the merge mining hash" is unclear. You have to either give it a proper name or say "the merge mining hash that follows the RSKBLOCK tag"

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +The ability to extend the merged mining process to include information other than the block’s hash in the merged mining hash offers a myriad of new applications to the miner’s hashing power without a
"new applications to the miner’s hashing power" is unclear. Maybe "new applications that can be secured by the same miner’s hashing power" ?

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +Potential applications may involve new mechanisms for other blockchains to do merged mining with RSK and by transitivity with BTC increasing their level of security.  Moreover, any kind of summarized
"by transitivity with BTC increasing their level of security" unclear.
Remove or rephrase.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +Recall that the merged mining hash consists of a 20-byte length prefix calculated as the keccak256 hash of the RSK block, followed by a 12-byte length string of information related to Armadillo (intr
"Recall" is informal. remove

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +1. Introduce a new 20-byte array field in the block called mergeMiningRightHash. This new field will contain the new information that is to be included in the new hash for merged mining. As this new
"in the block" -> "in the RSK block header". Try to specify which blockchain you're talking about since two blockchains are involved.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +1. Introduce a new 20-byte array field in the block called mergeMiningRightHash. This new field will contain the new information that is to be included in the new hash for merged mining. As this new
Define previously  "hash for merged mining" , so you can use it without ambiguity.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +1. Introduce a new 20-byte array field in the block called mergeMiningRightHash. This new field will contain the new information that is to be included in the new hash for merged mining. As this new
"As this new field is now part of the consensus protocol ..." don't explain why here, there is a section "Rationale" to explain why. Just say what the changes are.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +2. Change the way the hash for merged mining prefix is computed. Now instead of only using a hash of the block, a merkle tree will be built using the aforementioned block hash as the left leaf and th
"as the prefix instead" again the problem of not naming things, here is merge-mining hash is referred as "the prefix".

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +def buildHashForMergedMiningPrefix(block):
Now it's called "HashForMergedMiningPrefix". Slowly we're converging in a name.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +1. Introduce a new 20-byte array field in the block called mergeMiningRightHash. This new field will contain the new information that is to be included in the new hash for merged mining. As this new
You're not specifying where in the RLP encoding of the block header will this new field be located, nor the length of the field, nor what happens if the field is null or zero or too long.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +
The document should preferably include a "Security" section where you should explain why the change does not affect the security of RSK.

2020-10-08 19:36 UTC, SergioDemianLerner commented on IPs/RSKIP177.md
> +
A Rationale section is also suggested here, where you may comment why this design is better than alternatives, why the cost of adding this new field in terms of space or verification time is low.

2021-04-05 13:36 UTC, SergioDemianLerner approved these changes

2021-04-05 13:36 UTC, merged