Updated branding
rsksmart/RSKIPs pull request #364
Opened 2022-11-09 16:55 UTC by max-barrera-2148

Branding update first iteration

2022-11-10 07:56 UTC, bguiz approved these changes

2022-11-17 16:35 UTC, ilanolkies requested changes

2022-11-17 16:35 UTC, ilanolkies commented on _layouts/default.html
> +        <h2 id="rskips" class="orange-highlight">RSKIP</h2>
```suggestion
        <h2 id="rskips" class="orange-highlight">RSKIPs</h2>
```

2022-11-17 16:35 UTC, ilanolkies commented on _layouts/purpose.html
> +        <h2 id="rskips" class="orange-highlight">RSKIP</h2>
```suggestion
        <h2 id="rskips" class="orange-highlight">RSKIPs</h2>
```

2022-11-17 16:36 UTC, ilanolkies approved these changes

2022-11-17 16:36 UTC, merged